swagger: "2.0"
info:
  description: "This is a REST API to manage your lifestyle with family and friends."
  version: "1.0.0"
  title: "WebRep"
  contact:
    email: "tai.okubo93@gmail.com"
host: "localhost"
basePath: "/swagger-ui.html#/"

tags:
- name: "houses"
  description: "Access to all houses"
- name: "user"
  description: "Operations about user"

schemes:
- "https"
- "http"


paths:
  /houses:
    get:
      tags:
      - "houses"
      summary: "Returns all houses registered"
      description: "Returns a set of house objects as data"
      operationId: "getAllHouses"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Response"



securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"


definitions:
  Response:
    type: "object"
    properties:
      data:
        $ref: "#/definitions/ResponseData"
      meta:
        type: "object"
      errors:
        type: array
        items:
          type: object



  ResponseData:
    type: "object"
    properties:
      type:
        type: string
      id:
        type: integer
        format: int64
      attributes:
          $ref: "#/definitions/Attributes"

      relationships:
        $ref: "#/definitions/Relationships"


  Attributes:
    type: "object"


  Relationships:
    type: "object"

externalDocs:
  description: "Find out more about WebRep"
  url: "http://localhost:8080"